domain_path: D:\ACA_Group9\hd-aca-25-3\vitis_code\platform\export\platform\sw\standalone_microblaze_0
app_src_dir: F:\vivado\Vitis\2024.2\data\embeddedsw\lib\sw_apps\memory_tests
template: memory_tests
lang: c
